# Python CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.3

    working_directory: ~/repo

    steps:
      - checkout

      # Install
      - run:
          name: install dependencies
          command: |
            python3 -m venv boot
            . boot/bin/activate
            pip install -e .[test]
      # TEST
      - run:
          name: run tests
          command: |
            . boot/bin/activate
            tox